name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test & publish code coverage
      uses: amancevice/setup-code-climate@v0
      with:
        cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
    - run: cc-test-reporter before-build
    - run: npm install
    - run: npm run test
      env:
        CI: true
        TEST_DB: ${{ secrets.TEST_DB }}
        api_key: ${{ secrets.api_key }}
        api_secret: ${{ secrets.api_secret }}	
        cloud_name: ${{ secrets.cloud_name }}
        Secret: ${{ secrets.Secret }}
        expire: ${{ secrets.expire }}
    - run: cc-test-reporter after-build